### ISSUE TITLE
[Android] Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by flyingmate** [PhilippKrone/react-native-fileupload#1]
When I added "compile project(':react-native-fileupload')" to gradle.build 
and tried to gradle sync, I've got this error below.

"Gradle 'android' project refresh failed
Error:Configuration with name 'default' not found."

If I delete [compile project(':react-native-fileupload')] line, build passes.

When I tried to clean the build, I got more specific message like below. 
"Error:A problem occurred configuring project ':app'.

> Cannot evaluate module react-native-fileupload : Configuration with name 'default' not found."

I'm using react-native 0.14.0-rc

**Comment by PhilippKrone** [comment]
@flyingmate Thanks for opening the issue. I think there is a mistake in the README - could you please change the line

``` javascript
project(':react-native-fileupload').projectDir = new File(rootProject.projectDir, '../node_modules/fileupload/android')
```

to

``` javascript
project(':react-native-fileupload').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fileupload/android')
```

(Note the "react-native-fileupload" instead of just "fileupload").

Does that work?

Thanks
Philipp

**Comment by flyingmate** [comment]
@PhilippKrone, Thank you for the fix
Gradle sync passes, but I got another error when building.
Should I add facebook sdk to my project?

Thank you
James

/Users/james/Dropbox/Development/react/Builder/node_modules/react-native-fileupload/android/src/main/java/com/yoloci/fileupload/FileUploadModule.java:23: error: package com.facebook.internal does not exist
import com.facebook.internal.BundleJSONConverter;
                            ^
/Users/james/Dropbox/Development/react/Builder/node_modules/react-native-fileupload/android/src/main/java/com/yoloci/fileupload/FileUploadModule.java:159: error: cannot find symbol
                    BundleJSONConverter bjc = new BundleJSONConverter();
                    ^
  symbol:   class BundleJSONConverter
  location: class FileUploadModule
/Users/james/Dropbox/Development/react/Builder/node_modules/react-native-fileupload/android/src/main/java/com/yoloci/fileupload/FileUploadModule.java:159: error: cannot find symbol
                    BundleJSONConverter bjc = new BundleJSONConverter();
                                                  ^
  symbol:   class BundleJSONConverter
  location: class FileUploadModule

**Comment by PhilippKrone** [comment]
@flyingmate I've just published v1.1, in which I've included the bode of BundleJSONConverter to not rely on the SDK here. Could you please test this?

Thanks! :)

**Comment by flyingmate** [comment]
@PhilippKrone Build success :)
Thank you

P.S. Now, I'm trying to upload camera/gallery images to parse.com server using this library

**Comment by bhagwanverma11** [comment]
hello anyone solve the Error
Error:Configuration with name 'default' not found.
