### ISSUE TITLE
Can't get image data

### ISSUE THREAD

**Issue by wengbenjue** [PhilippKrone/react-native-fileupload#10]
I can't upload image binary in android.

here is my android file path

constructor(props) {
super(props);
this.state = {
avatarSource: null,
videoSource: null
};
var obj = {
uploadUrl: 'http://192.168.50.161:8080/soledede/image',
method: 'POST', // default 'POST',support 'POST' and 'PUT'
headers: {
'Accept': 'application/json',
//'Accept': 'multipart/form-data',
//'Content-type': 'multipart/form-data'
//'Content-Disposition': 'form-data; name="file"',
},
fields: {
'hello': 'world',
},
files: [
{
name: 'image', // optional, if none then filename is used instead
filename: '1007044', // require, file name

filepath: 'content://media/external/images/media/1007044', // require, 
filetype: 'image/png,image/gif,image/jpeg', 
},
]
};
FileUpload.upload(obj, function (err, result) {
console.log('upload:', err, result);
});
}

there is my debug in chrome
image

what's like the android file path ,can show me a example

How can I deal with it in android

Thanks

soledede

**Comment by wengbenjue** [comment]
the debug in chrome
![image](https://cloud.githubusercontent.com/assets/5533297/12314381/86e3ef9e-baab-11e5-9ce4-77486436f29f.png)

the question is how can I convert the content://media/external/images/media/1007044 to the absolute filepath

why return the content uri for react native

I need help 

Thanks

**Comment by wengbenjue** [comment]
according rewrite the sourcecode alittle, I have solve this proplem

**Comment by skyride99** [comment]
@wbj0110 ,

I am having a similar problem. What was the rewrite?
