### ISSUE TITLE
Can't upload with android 

### ISSUE THREAD

**Issue by wengbenjue** [PhilippKrone/react-native-fileupload#11]
I have a problem
![image](https://cloud.githubusercontent.com/assets/5533297/12414394/327001e0-bed0-11e5-9649-52c3b9985712.png)

err = "Error happened: TypeError: expected dynamic type `string', but had type`int64'"
This my debug env,who can help me

I using react-native 0.18.0

**Comment by wengbenjue** [comment]
Who can tell me why

**Comment by yerevin** [comment]
did u solved this problem? I have same now
