### ISSUE TITLE
Build fails on React Native 0.15 for Android

### ISSUE THREAD

**Issue by BigPun86** [PhilippKrone/react-native-fileupload#2]
Hey there,

i would love to use this but i get following error:

```
node_modules/react-native-fileupload/android/src/main/java/com/yoloci/fileupload/FileUploadModule.java:23: error: package com.facebook.internal does not exist import com.facebook.internal.BundleJSONConverter;
```

**Comment by PhilippKrone** [comment]
Hi,

can you try to remove line 23 from FileUploadModule.java and see whether this fixes the error?

Thanks
Philipp

**Comment by BigPun86** [comment]
Hey there. I solved it by changing the import in FileUploadModule from:

```
import com.facebook.internal.BundleJSONConverter;
```

to:

```
import com.yoloci.fileupload.BundleJSONConverter;
```

Is this the right solution? I didn´t get any issue...

**Comment by PhilippKrone** [comment]
Yea, thats fine. I'm gonna update it right away. Thanks for telling me!

**Comment by BigPun86** [comment]
No prob, thanks for the great module :)
