### ISSUE TITLE
run-android failed

### ISSUE THREAD

**Issue by hongjie104** [PhilippKrone/react-native-fileupload#4]
hi,i use commad "react-native run-android",then failed...
react-native : 0.16.0

log:
:react-native-fileupload:compileReleaseJavaWithJavacF:\apowo\PTuApp\client\truck\P2_16\node_modules\react-native-fileupload\android\src\main\java\com\yoloci\fileupload\FileUploadModule.java:23: ▒▒▒▒: ▒▒▒▒▒com.facebook.internal▒▒▒▒▒▒
import com.facebook.internal.BundleJSONConverter;

I do not know Why...

**Comment by kazaff** [comment]
me too~

**Comment by PhilippKrone** [comment]
Please use the master from this repo instead of the current NPM version. Moreover, please check the closed issues for more details.

Regards
Philipp

**Comment by kazaff** [comment]
thank you
