### ISSUE TITLE
RCTBridgeModule.h FILE NOT FOUND

### ISSUE THREAD

**Issue by ghost** [PhilippKrone/react-native-fileupload#41]
1. In XCode, in the project navigator, right click your project ➜ Add Files to [your project's name]
2. Go to node_modules ➜ react-native-fileupload and add FileUpload.m
3. Run your project (Cmd+R)

Followed this step and stuck at this error. i am checking this module on ios.

**Comment by sushant6309** [comment]
@o-vp-v How you fixed this issue.
