### ISSUE TITLE
upload: Error happened: favoriteFilled.png: open failed: ENOENT (No such file or directory) null

### ISSUE THREAD

**Issue by cspkop** [PhilippKrone/react-native-fileupload#7]
@PhilippKrone - Where to keep the file which is to be uploaded?
In Below documentation, what does absolute path means? Where to keep the file? '/' refers to which root folder - apps root folder( where index.android.js resides) OR to mobiles handset file system?
files: [
          {
            name: 'one', // optional, if none then `filename` is used instead
            filename: 'one.w4a', // require, file name
            filepath: '/xxx/one.w4a', // require, file absoluete path
            filetype: 'audio/x-m4a', // options, if none, will get mimetype from `filepath` extension
          },
        ]

In my code, I kept png file in apps root folder, and used following code but it gives above error. 
filename: 'favoriteFilled.png', 
filepath: 'favoriteFilled.png', 

I have tried giving filepath as:
 'filepath: '/favoriteFilled.png', 
'filepath: './favoriteFilled.png' 
But, still same error I get.

**Comment by PhilippKrone** [comment]
@cspkop You have to use an absolute path and not a RN asset. Take a look here: http://stackoverflow.com/questions/4044376/get-image-paths-from-nsbundle-in-objective-c

Otherwise, better post such a question in stack-overflow, as that has nothing to do with this module really. :)

**Comment by leoabacade** [comment]
using : "version": "1.2.0",
running on : 'Nexus 6 - 5.0.1' with apk '23'

the image shows up at `<Image style={styles.displaied} source={{ uri: 'file:/storage/emulated/0/DCIM/Camera/IMG_20160211_125509.jpg' }}/>`

but while am trying to upload to server, i got:

`upload: Error happened: file:/storage/emulated/0/DCIM/Camera/IMG_20160211_125509.jpg: open failed: ENOENT (No such file or directory)`

below are codes,

```
var obj = {
                uploadUrl: fileLoc + 'file_upload_handler',
                method: 'POST', // default 'POST',support 'POST' and 'PUT' 
                headers: {
                  'Content-Type': 'image/jpeg'
                },
                fields: {
                    'img': uri,
                    'id': this.state.responseData.id,
                    'token': this.state.responseData.token,
                },

                files: [
                  {
                    name: 'one.jpeg', // optional, if none then `filename` is used instead 
                    filename: 'one.jpeg', // require, file name 
                    filepath: uri, // require, file absoluete path 
                    filetype: 'image/jpeg', // options, if none, will get mimetype from `filepath` extension 
                  },
                ]
            };

            FileUpload.upload(obj, function(err, result) {
              console.log('upload:', err, result);
            });
```

any ideas?

**Comment by leoabacade** [comment]
got it working by change below scripts:

＠react-native var obj
from:
`headers: { 'Content-Type': 'image/jpeg' },`
to:
`headers: { 'Accept': 'application/json'},`

＠server-end php script
from:
`$_FILES["file"]["tmp_name"];`
to: 
`$_FILES["image"]["tmp_name"];`
